### ISSUE TITLE
Publish library to pypi

### ISSUE THREAD

**Issue by hhalaby** [usgs/earthquake-impact-utils#151] opened 2022-11-22 10:04 UTC
Is it possible to publish this library to pypi by adding requirements to setup.py ?

**Comment by mhearne-usgs** [comment] 2022-11-22 14:58
@hhalaby We are in the process of moving this repository (and a number of others) from GitHub to a USGS Gitlab instance. The functionality in this library is being split up into several smaller packages, all but one of which will be pip installable from PyPI.

When we are finished, we will archive this repository and put a notice in the README pointing to the new repository locations and the pip installable names.

**Closed by mhearne-usgs** 2022-11-22 14:58 UTC

**Comment by hhalaby** [comment] 2022-11-22 15:37
@mhearne-usgs thanks for the answer, this is quite a positive change for us !
 
Is it possible to know which functionalities will not be installable from PyPI ? 

Is there also any planned or rough timeline as to when the move will be completed ?

**Comment by hhalaby** [comment] 2022-11-22 16:13
This seems like great news for us, we are not using cartopy from impact-utils as far as I know. We will test things out and let you know.

**Comment by emthompson-usgs** [comment] 2022-11-22 17:28
Yes, @mhearne-usgs is currently working on getting libcomcat through this same process. I expect he will be done soon but we can't promise a specific timeline.

**Comment by hhalaby** [comment] 2022-12-19 07:49
@emthompson-usgs hello
I recently opened an issue on the libcomcat GitHub but I'm not sure if it's still active or not. 

I've tried installing libcomcat from pypi but the required version only allows Python 3.10.0 and no other higher minor version. Is this intended or can it be fixed?

**Comment by emthompson-usgs** [comment] 2022-12-19 14:53
@hhalaby Thank you for the reminder, and the original bug report. I had started to address this last week but ended up getting too busy with other tasks. This is not the intended behavior and should be fixed.

**Comment by hhalaby** [comment] 2022-12-22 10:39
@emthompson-usgs  thank you for the christmas gift !

**Comment by emthompson-usgs** [comment] 2022-12-27 21:10
Just noticed that this was still open. Closed by this merge request: 
https://code.usgs.gov/ghsc/esi/libcomcat-python/-/merge_requests/277
